version: '3'

services:

  nginx:
    image: "antonio29398/nginxwebrtc:latest"
    container_name : 'nginx'
    ports:
    - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl

    restart: always
    networks:
      network_compose:
        ipv4_address: 194.20.1.2



  mysql:
    image: "mysql:latest"
    container_name : 'database'
    
    environment:
    # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

    restart: always
    networks:
      network_compose:
        ipv4_address: 194.20.1.3
        
    
  
  janus:
    image: "antonio29398/janus-gateway:v3"

    container_name: 'janus'

    command:  bash -c "/opt/janus/bin/janus "

    ports: 
    - "8088:8088"
  
    restart: always
    networks:
      network_compose:
        ipv4_address: 194.20.1.4
      
  

  server:
    image: "antonio29398/ubuntuserver:v5"
    container_name : 'server'
    
    
    volumes:
    - ./:/home/ProgettoWebRTC

    command: bash -c " ./home/ProgettoWebRTC/startup.sh " 
     

    restart: on-failure
    networks:
      network_compose:
        ipv4_address: 194.20.1.5
    
      
networks:
  network_compose:
    ipam:
      config:
         - subnet: 194.20.1.1/24

  


